name: Generate README

# Trigger workflow on push to the main branch or pull requests targeting main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Python dependencies (if needed)
      - name: Install dependencies
        run: pip install pandas

      # Step 4: Run the script to generate README.md
      - name: Generate README.md
        run: python generate_readme.py

      # Step 5: Commit and push the updated README.md back to the repository
      - name: Commit and Push README.md
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Auto-generate README.md [skip ci]" || echo "No changes to commit"
          git push
